[package]
name = "crashing-cars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy_rapier2d = "0.17.0"
leafwing-input-manager = "0.6.1"